apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  replicas: 2  # Number of replicas
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: repodir/boardproject:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080  # Port inside the container

---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service  # Changed service name for clarity
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # If running in Minikube, Consider NodePort
